const letterData = [
  {
    "itemNo": "आइटम २९",
    "officeName1": ["राष्ट्रिय सूचना आयोग"],
    "officeName2": [""],
    "contactInfo": [""],
    "department": "",
    "mainOffice": "",
    "entryNo": "",
    "entryDate": "",
    "dispatchedNo": "",
    "caseNo": "",
    "date": "",
    "subject": "",
    "addressedTo": [""],
    "content": "112",
    "images": [
      { "src": "nepali_government_emblem.png", "position": "left" },
      { "src": "national_information_commission_logo.png", "position": "right" }
    ],
    "signature1": { "sign": "", "name": "", "position": "" },
    "signature2": { "sign": "", "name": "", "position": "" },
    "footerPhone": "",
    "footerEmail": "",
    "tokadesh": "",
    "bodharthaList": [""],
    "emptyPage": "NO",
    "emptyEntry": []
  },
  {
    "itemNo": "आइटम ३०",
    "officeName1": ["नेपाल सरकार", "उद्योग वाणिज्य तथा आपूर्ति मन्त्रालय"],
    "officeName2": ["उद्योग विभाग", "(विदेशी लगानी तथा प्रविधि हस्तान्तरण शाखा)"],
    "contactInfo": ["त्रिपुरेश्वर, काठमाडौं नेपाल"],
    "department": "",
    "mainOffice": "",
    "entryNo": "प. सं.  २०७९/८०",
    "entryDate": "च.नं. ८५१",
    "dispatchedNo": ["दर्ता नं. २१२", "दर्ता मितिः२०७९।११।२०"],
    "caseNo": "",
    "date": "मिति:- २०७९.११.१६",
    "subject": "व्यवसायिक भिसा सिफारिस सम्बन्धमा।",
    "addressedTo": ["श्री फकल बिन्दु सेवा केन्द्र,", "भिसा सहजीकरण इकाई,", "त्रिपुरेश्वर, काठमाडौं।"],
    "content": "11",
    "images": [],
    "signature1": { "sign": "", "name": "", "position": "शाखा अधिकृत" },
    "signature2": { "sign": "", "name": "", "position": "" },
    "footerPhone": "४२६११०१, ४२६१२०३, ४२६११७८, ४२६१११३, फ्याक्स: ९७७-१-४२६१११२",
    "footerEmail": "info@doind.gov.np",
    "tokadesh": "(कृपया पत्राचार गर्दा पत्र संख्या र मिति उल्लेख गर्नुहोला।)",
    "bodharthaList": ["श्री होटल विन्डफुल, undefined"],
    "emptyPage": "NO",
    "emptyEntry": [
      {
        "sn": "१",
        "name": "Ms Hyunkyung Kim",
        "country": "Korea, Republic of",
        "passportNo": "M34174759",
        "duration": "2021-11-03 To 2023-05-26",
        "remarks": "Investor"
      }
    ]
  },
  {
    "itemNo": "आइटम ०",
    "officeName1": [""],
    "officeName2": [""],
    "contactInfo": [""],
    "department": "",
    "mainOffice": "",
    "entryNo": "",
    "entryDate": "",
    "dispatchedNo": "",
    "caseNo": "",
    "date": "",
    "subject": "",
    "addressedTo": [""],
    "content": "",
    "images": [],
    "signature1": { "sign": "", "name": "", "position": "" },
    "signature2": { "sign": "", "name": "", "position": "" },
    "footerPhone": "",
    "footerEmail": "",
    "tokadesh": "",
    "bodharthaList": [""],
    "emptyPage": "YES",
    "emptyEntry": [
      "यो एउटा खाली पृष्ठ हो",
      "flower.png",
      "contact the compiler for enabling this inbasket exercise",
      "https://source.unsplash.com/featured/800x600"
    ]
  }
];
